apiVersion: v1
kind: Service
metadata:
  name: basket-prod-lb
  labels:
    app: basket-prod
  namespace: basket-prod
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:236517346949:certificate/d6d41a56-17fd-4588-bd32-cdd1c4174ec8"
     external-dns.alpha.kubernetes.io/hostname: "basket-prod.frankfurt.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  selector:
    app: basket-prod
    type: web
