apiVersion: v1
kind: Service
metadata:
  name: basket-prod-lb
  labels:
    app: basket-prod
  namespace: basket-prod
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:236517346949:certificate/ce86f1b1-7020-432f-9f79-b05c1e301d8e"
     external-dns.alpha.kubernetes.io/hostname: "prod-oregon-b.basket.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  selector:
    app: basket-prod
    type: web
