apiVersion: v1
kind: Service
metadata:
  name: basket-admin-stage-lb
  labels:
    app: basket-admin-stage
  namespace: basket-admin-stage
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:236517346949:certificate/8470c4e1-2acd-4e6e-b5e8-9e9560caa2c0"
     external-dns.alpha.kubernetes.io/hostname: "admin-stage.basket.moz.works,basket-admin-stage.us-west.moz.works,admin-stage-oregon-b.basket.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  selector:
    app: basket-admin-stage
    type: web
