apiVersion: v1
kind: Service
metadata:
  name: basket-dev-lb
  labels:
    app: basket-dev
  namespace: basket-dev
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:236517346949:certificate/5b7b7e99-dd57-4bce-92ea-c1a2534340bb"
     external-dns.alpha.kubernetes.io/hostname: "basket-dev.moz.works,dev-oregon-b.basket.moz.works,basket-dev.oregon-b.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  selector:
    app: basket-dev
    type: web
