apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: basket-stage
  name: basket-nodeport
  namespace: basket-stage
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32389
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-stage
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
