apiVersion: v1
kind: Service
metadata:
  name: basket-stage-lb
  labels:
    app: basket-stage
  namespace: basket-stage
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:236517346949:certificate/0c02d92c-c9cd-4e51-b397-ed49bb851a66"
     external-dns.alpha.kubernetes.io/hostname: "basket-stage.frankfurt.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  selector:
    app: basket-stage
    type: web
